<h1 style=\"text-align: center\">lab_05, Artur Żarnoch, <b>162686</b></h1>
<hr />

<h2>Zadanie 1</h2>
<p>Zdefiniuj następujące zbiory, wykorzystując Python comprehension:
<pre>
A = {1/x: x∈[1,10]}
B = {1, 2, 4, 8,…, 2^10}
C = {x: x∈ B i x jest liczbą podzielną przez 4}</pre></p>

In [1]:
A = [1/i for i in range(1, 11)]
B = [2**i for i in range(0, 11)]
C = [i for i in B if i % 4 == 0]

print(f"A = {{1/x: x∈[1,10]}}: {A}")
print(f"B = {{1, 2, 4, 8,…, 2^10}}: {B}")
print(f"C = {{x: x∈ B && x % 4 == 0}}: {C}")

A = {1/x: x∈[1,10]}: [1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1]
B = {1, 2, 4, 8,…, 2^10}: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
C = {x: x∈ B && x % 4 == 0}: [4, 8, 16, 32, 64, 128, 256, 512, 1024]


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 2</h2>
<p>Wygeneruj macierz (lista dwupoziomowa) losowych wartości (sprawdź pakiet `random`) 4x4 i wykorzystując Python comprehension zdefiniuj listę, która będzie zawierała tylko elementy znajdujące się na głównej przekątnej.</p>

In [2]:
import random
import numpy as np


rows = 4
cols = 4

matrix = [[random.randint(0, 9) for _ in range(cols)] for _ in range(rows)]

diagonal = [element[idx] for idx, element in enumerate(matrix) if matrix.index(element) == idx]

print(f"Macierz wynikowa: {matrix}")
print(f"Główna przekątna: {diagonal}")
print(f"Główna przekątna wydobyta biblioteką NumPy: {np.diag(matrix)}")

np_matrix = np.array(matrix)
print(f"\nMacierz wyświetlona za pomocą NumPy:\n{np_matrix}")
print(f"\nMacierz diagonalna:\n{np.diag(diagonal)}")

Macierz wynikowa: [[6, 6, 0, 9], [1, 6, 7, 2], [9, 6, 1, 9], [3, 7, 7, 6]]
Główna przekątna: [6, 6, 1, 6]
Główna przekątna wydobyta biblioteką NumPy: [6 6 1 6]

Macierz wyświetlona za pomocą NumPy:
[[6 6 0 9]
 [1 6 7 2]
 [9 6 1 9]
 [3 7 7 6]]

Macierz diagonalna:
[[6 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 6]]


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 3</h2>
<p>Napisz wyrażenie generujące, które będzie zwracało krotkę dwuwartościową postaci: <pre>('Ala', [65, 108, 97]), ('ma', [109, 97]), ('kota.', [107, 111, 116, 97, 46])</pre> dla przykładowego zdania <pre>Ala ma kota</pre>. Dla każdego wyrazu z tekstu przekazanego jako argument wejściowy tego wyrażenia zwraca ten wyraz oraz listę wartości int odpowiadającą kodowi tego znaku z tablicy znaków (zobacz wbudowane ord(), chr()).</p>

In [3]:
sentence = "Ala ma kota"

result = ((word, [ord(char) for char in word]) for word in sentence.split())

for item in result:
    print(item)

result = ((word, [ord(char) for char in word]) for word in sentence.split())
recovered_sentence = " ".join("".join([chr(val) for val in tup[1]]) for tup in result)
print(recovered_sentence)

('Ala', [65, 108, 97])
('ma', [109, 97])
('kota', [107, 111, 116, 97])
Ala ma kota


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 4</h2>
<p>Dodaj do funkcji z listingu 8 type hinting.</p>

In [4]:
import math
from typing import Tuple


def row_kwadratowe(a: int | float, b: int | float, c: int | float) -> int | float | Tuple[float, float]:
    delta: int = b**2 - 4 * a * c
    if (delta < 0):
        # brak pierwiastków
        return -1
    elif (delta == 0):
        # jeden pierwiastek
        x: float = (-b) / (2 * a)
        return x
    else:
        # równanie ma dwa pierwiastki
        x1: float = (- b - math.sqrt(delta)) / (2 * a)
        x2: float = (- b + math.sqrt(delta)) / (2 * a)
        return x1, x2

print(row_kwadratowe(6,1,3))
print(row_kwadratowe(1,2,1))
print(row_kwadratowe(1,4,1))
# dodany przykład:
print(row_kwadratowe(1.5, 6, 1.33))

-1
-1.0
(-3.732050807568877, -0.2679491924311228)
(-3.764464035715473, -0.23553596428452708)


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 5</h2>

<p>Napisz funkcję, która:
<ul>

<li>przyjmuje z klawiatury n, będące liczbą całkowitą,</li>
<li>wykonuje n rzutów kostką k6 i zwraca listę krotek wartości postaci ('oczka: 6', 'rzutów: i') itd., gdzie zmienna i jest ilością rzutów dla tej liczby oczek. Dodaj odpowiedni type hinting.</li></ul></p>

In [5]:
import random
from typing import Dict, List, Tuple


n: str = input("Wprowadź liczbę całkowitą:")

while not n.isnumeric():
    n = input("Błąd. Wprowadź liczbę całkowitą:")

n: int = int(n)


def throwK6Dice(throws: int) -> List[Tuple[str, str]]:
    throws_dict: Dict[int, int] = {}
    for i in range(1, 7):
        throws_dict[i] = 0

    for i in range(0, throws):
        throw: int = random.randint(1, 6)
        throws_dict[throw] = throws_dict[throw] + 1

    throws_list: List[Tuple[str, str]] = []
    for key, val in throws_dict.items():
        throws_list.append((f"oczka: {key}", f"rzutów: {val}"))

    return throws_list


print("Ilość rzutów:", n)
print(throwK6Dice(n))

Ilość rzutów: 100
[('oczka: 1', 'rzutów: 13'), ('oczka: 2', 'rzutów: 11'), ('oczka: 3', 'rzutów: 19'), ('oczka: 4', 'rzutów: 18'), ('oczka: 5', 'rzutów: 16'), ('oczka: 6', 'rzutów: 23')]


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 6</h2>

<p>Wykorzystując poprzedni przykład z listingu 11 zdefiniuj funkcję, która będzie przyjmowała obiekty typu `str` jako wejście (dowolną liczbę), a będzie zwracała listę tych łańcuchów posortowaną alfabetycznie.</p>

In [6]:
def sort_strings(*napisy: Tuple[str]):
    # jeżeli nie ma argumentów to
    if len(napisy) == 0:
        return []
    else:
        return sorted(napisy)

# wywołanie gdy brak argumentów
print(sort_strings())
# podajemy argumenty
print(sort_strings("x", "d", "h", "l", "p", "c", "z", "a", "s", "e"))

[]
['a', 'c', 'd', 'e', 'h', 'l', 'p', 's', 'x', 'z']


<hr style=\"height: 3px; background-color: black;\" />
<h2>Zadanie 7</h2>

<p>Napisz funkcję, która przyjmuje nieokreśloną liczbę wartości z kluczem. Funkcja przyjmuje argumenty w postaci: klucz to nazwa drużyny a wartość to ilość punktów, które drużyna zdobyła. Funkcja zlicza, ile jest wszystkich punktów razem i zwraca tę wartość.</p>

In [7]:
def sumTeamsPoints(**teams_with_points):
    return sum(teams_with_points.values())


print("Suma punktów wszystkich zespołów:", sumTeamsPoints(ManUnited=89, ManCity=78, Chelsea=75, Arsenal=73, Tottenham=72, Everton=63))

Suma punktów wszystkich zespołów: 450
